[package]
authors = ["Erik Johnston <erikj@matrix.org>"]
name = "matrix-ircd"
version = "0.1.0"

[dependencies]
clap = "2.14.0"
futures = "0.1.1"
httparse = "1.1.2"
lazy_static = "0.2.1"
native-tls = "0.2.2"
netbuf = "0.4.0"
pest = "0.4.0"
quick-error = "1.1.0"
rand = "0.3.14"
regex = "1.5.5"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
slog = "2.0.0"
slog-async = "2.0.0"
slog-term = "2.0.0"
tokio-core = "0.1.0"
tokio-dns-unofficial = "0.1.0"
tokio-io = "0.1.3"
tokio-proto = "0.1.0"
tokio-tls = "0.2.0"
url = "1.2.1"

[dependencies.openssl]
version = "0.10.0"

[dependencies.tasked-futures]
git = "https://github.com/erikjohnston/tasked-futures.git"
optional = false

[dependencies.tokio-timer]
git = "https://github.com/tokio-rs/tokio-timer"

[features]
clippy = []
default = []
trace_logging = [
    "slog/max_level_trace",
    "slog/release_max_level_warn",
]
